# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35f3ceffd9a5f39a736abcdcd2649db16b4585c3d32ce53939daf47979c15381a0c536701ad80aa92f104bddcb6018a8107183fed4066094888d34a3ece85923

test:
  secret_key_base: 6ff3fe4f3108fc4a13f5da957ce423203ad6d1e9f2c1d39d16433aa47f5559c77fadb054a936557eb1fb03daf39ed36e492c4e252aa517463d4af04f8f915fea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
